BienesRaices/urls.py
from django.contrib import admin
from django.urls import path, include # include para incluir otras url de otras aplicaciones ejm: 'blog'

# Para acceder a los archivos statics y media desde el navegador.
from django.conf import settings
from django.conf.urls.static import static

""" PARA ACCEDER A LOS ESQUEMAS CREADOS archivo.yml desde la web, tenemos que establecer las url's """
from drf_spectacular.views import (SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView)


# Tambien conocidos como EndPoints => Hablando de documentación de Apis
urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # URL de Autenticacion y Autorización de Django
    path('api/v1/', include("api.urls", namespace ="api-rest")), # Registramos las Urls de nuestra API
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'), # url_name='schema' => el name coincide con el name de SpectacularAPIView.as_view()
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path("", include("main.urls", namespace="main")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("signup-users/", include("users.urls", namespace="signup-users")),
    path("chat/", include("chat.urls", namespace="chat-room")),
    path("social-auth/", include("social_django.urls", namespace="social")),  # <-- Social Media
]

# if settings.DEBUG === True
# Configuración para servir archivos de medios solo durante el desarrollo.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# usamos routers en lugar de path, ya que nos permiten hacer varias operaciones
# que gestiona Django como un CRUD (get, post, delete, etc..)
from rest_framework import routers
from .views import PropiedadesViewSet

app_name = "api_propiedades"

router = routers.DefaultRouter()  # Es clave porque lo gestiona Django (get, post, delete, etc..)
router.register("propiedades", PropiedadesViewSet, "propiedades_api")

urlpatterns = router.urls

blog/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

app_name = "namespaceblog"

urlpatterns = [
    path("", views.viewBlog, name="blog_list"),
    path("<int:id>/", views.viewBlogDetail, name="blog_details"),  # <int:id> una url dinámica con el ID de cada BLOG
    path("blog-register/", views.viewCreateBlog, name="blog-register"),
    path("check_user_createBlog/", views.check_user_createBlog, name="check_user_createBlog"),
]

main/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas
# Tambien se puede acceder => views.my_main.etc

app_name = "namespaceraices"

urlpatterns = [
    path("", views.my_main, name="main"),
    path("nosotros/", views.nosotros, name="nosotros"),
    path("anuncios/", views.anuncios, name="anuncios"),
    path("<int:id>/", views.anuncio_detalles, name="anuncio_detalles"),
    path("contacto/", views.contacto, name="contacto"),
    path("testimoniales/", views.viewTestimoniales, name="testimonials"),
    path("check_user_testimonial/", views.check_user_testimonial, name="check_user_testimonial"),
]

main/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Clientes(models.Model):
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    telefono = models.IntegerField()
    email = models.EmailField()
    fecha_alta = models.DateField(default=timezone.now)  # Valor por defecto: fecha actual

    # es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.nombre


class Vendedores(models.Model):
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    telefono = models.IntegerField()
    email = models.EmailField()
    fecha_alta = models.DateField(default=timezone.now)
    # es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.nombre


class Propiedades(models.Model):
    titulo = models.CharField(max_length=45)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    img = models.ImageField(upload_to="images/")  # null=True, blank=True => blank indica que el campo no es obligatorio
    descripcion = models.CharField(max_length=260)
    contentido = models.TextField()
    habitaciones = models.IntegerField()
    wc = models.IntegerField()
    garaje = models.IntegerField()
    fecha_alta = models.DateField(default=timezone.now)
    vendido = models.BooleanField(default=False)
    # es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.titulo

    # cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE, null=True, blank=True)
    # vendedor = models.ForeignKey(Vendedores, on_delete=models.CASCADE, null=True, blank=True)


""" Django requiere la biblioteca Pillow para manejar imágenes. 
Pillow es una biblioteca de procesamiento de imágenes para Python que Django utiliza para manejar campos de imagen """
# python -m pip install Pillow


class Ventas(models.Model):
    cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(Vendedores, on_delete=models.CASCADE)
    propiedad = models.ForeignKey(Propiedades, on_delete=models.CASCADE)
    fecha_venta = models.DateField(default=timezone.now)
    # es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.cliente.nombre


class Propiedad_Vendedor(models.Model):
    propiedad = models.ForeignKey(Propiedades, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(Vendedores, on_delete=models.CASCADE)
    fecha_alta = models.DateField(default=timezone.now)

    # es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.vendedor.nombre

main/forms.py
import re
from django import forms
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.utils.html import escape

# OBLIGATORIO, si queremos que se registre en la DB, debemos inportar como en admin.py
from users.models import Testimoniales


class ContactForm(forms.Form):
    # ======== Campos de información personal ========
    nombre = forms.CharField(
        label="Nombre completo",
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Ingrese su nombre"}),
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={"placeholder": "Ingrese su email"}),
    )
    
    telefono = forms.CharField(
        label="Teléfono",
        max_length=15,  # Puedes ajustar el max_length según sea necesario
        widget=forms.TextInput(
            attrs={"placeholder": "Ingrese su teléfono", "type": "tel"}
        ),
    )
    mensaje = forms.CharField(
        label="Mensaje",
        widget=forms.Textarea(
            attrs={"placeholder": "Escriba un breve mensaje"}
        ),
    )

    # Definir fieldsets como una lista de tuplas
    fieldsets = [
        ("Información personal", ["nombre", "email", "telefono", "mensaje"]),
        # ("Información sobre la propiedad", ["venta_compra", "presupuesto"]),
        # ("Método de contacto", ["contacto", "fecha", "hora"]),
    ]

    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"].strip()
        return escape(nombre)

    def clean_email(self):
        email = self.cleaned_data.get("email").strip()
        try:
            validate_email(email)
        except ValidationError:
            raise forms.ValidationError("Por favor, ingrese un correo electrónico válido.")
        return escape(email)

    def clean_telefono(self):
        telefono = self.cleaned_data.get("telefono").strip()
        # Definir la expresión regular
        phone_regex = re.compile(r'^(?:\+\d{1,3}\s?\d{3}|\d{3})\s?\d{3}\s?\d{3}$')

        # Validar el teléfono contra la expresión regular
        if not phone_regex.match(telefono):
            raise ValidationError("El número de teléfono no es válido. Debe seguir el formato adecuado.")

        # Escapar cualquier carácter potencialmente peligroso
        return escape(telefono)

    def clean_mensaje(self):
        mensaje = self.cleaned_data["mensaje"].strip()
        return escape(mensaje)


class TestimonialForm(forms.ModelForm):

    contenido = forms.CharField(label="Contenido", widget=forms.Textarea, required=True)

    def clean_contenido(self):
        contenido = self.cleaned_data["contenido"].strip()
        max_characters = 250  # define el máximo de caracteres permitidos
        content_regex = re.compile(r'^[a-zA-ZÀ-ÿ0-9\s.,¡!¿?()\-"\'\']+$')

        if len(contenido) > max_characters:
            raise forms.ValidationError(
                f"El contenido no puede tener más de {max_characters} caracteres"
            )

        if not content_regex.match(contenido):
            raise forms.ValidationError(
                "El contenido solo puede contener letras, números, y algunos signos de puntuación permitidos."
            )

        return escape(contenido)


    class Meta:
        model = Testimoniales
        fields = [
            "contenido"
        ]

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.utils.html import escape
from django.http import Http404


# descorador para validar si el usuario esta autenticado
from django.contrib.auth.decorators import login_required

# libreria para enviar un correo electronico
from django.core.mail import send_mail

# Importamos los modelos o formularios
from .models import Propiedades
from users.models import Testimoniales
from blog.models import Blog  # Importa el modelo Blog de la app blog
from .forms import ContactForm
from .forms import TestimonialForm


# Create your views here.

def my_main(request):
    # Obtener los tres primeros elementos de Propiedades
    solo_tres_propiedades = Propiedades.objects.filter(vendido=False)[:3]

    # Obtener los dos primeros elementos de Blog
    solo_dos_blog = Blog.objects.all()[:2]

    # Testimoniales
    testimoniales_result = Testimoniales.objects.all()

    return render(request, "plantillas/index.html", {"solo_tres": solo_tres_propiedades, "solo_dos": solo_dos_blog, "testimoniales": testimoniales_result})


def nosotros(request):
    return render(request, 'plantillas/nosotros.html')


# descorador para validar si el usuario esta autenticado
@login_required
def viewTestimoniales(request):

    user = request.user

    # Verificar si el usuario ya tiene una reseña
    if Testimoniales.objects.filter(usuario=user).exists():
        messages.error(request, "Ya has escrito una reseña")

    if request.method == "POST":
        form = TestimonialForm(request.POST)
        if (form.is_valid()):  # valida  los campos del formulario, que no esten vacios, etc

            # Si el formulario es válido, guardamos el blog en la base de datos
            new_testimonials = form.save(commit=False)
            new_testimonials.usuario = (request.user)  # Establecer el nombre del titular como el nombre de usuario autenticado
            new_testimonials.save()

            # Guarda el nuevo registro en BD
            new_testimonials = form.save()
            messages.success(request, "¡Reseña creada con éxito!")
            # Redirecciona a un Url
            return redirect("namespaceraices:main")
    else:
        form = TestimonialForm()

    return render(request, "plantillas/testimoniales.html", {"form_testimoniales": form})


# Endpoind de verificacion de usuario y evitar que vuelva a escribir
@login_required
def check_user_testimonial(request):
    user = request.user
    has_testimonial = Testimoniales.objects.filter(usuario=user).exists()
    return JsonResponse({"has_testimonial": has_testimonial})


def anuncios(request):
    # query_result = Propiedades.objects.all()
    query_result = Propiedades.objects.filter(vendido=False)
    return render(request, "plantillas/anuncios.html", {"clave": query_result})


def anuncio_detalles(request, id):
    try:
        # busca el registro cuyo ID es igual al pasado por URL
        detail = Propiedades.objects.get(id=id)
    except Propiedades.DoesNotExist:
        # Si no existe ese ID lanza la excepcion DoesNotExist y capturada con un try-except
        raise Http404("La Propiedad no existe")

    return render(request, "plantillas/anuncio.html", {"details": detail})


def contacto(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            # Aquí puedes acceder a los datos del formulario validado
            nombre = form.cleaned_data["nombre"]
            email = form.cleaned_data["email"]
            telefono = form.cleaned_data["telefono"]
            mensaje = form.cleaned_data["mensaje"]

            # Aquí puedes hacer lo que quieras con los datos del formulario,
            # como enviar un correo electrónico, almacenarlos en la base de datos, etc.

            # Después de manejar los datos del formulario, puedes redirigir o renderizar una plantilla
            return render(request, "plantillas/contacto.html", {"success": True})
    else:
        initial_data = {
            "nombre": request.user.username if request.user.is_authenticated else ""
        }
        form = ContactForm(initial=initial_data)

    return render(request, "plantillas/contacto.html", {"formContacto": form})

main/templates/plantillas/anuncios.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>

<main class="contenedor comodin">
    <h2>Casas y Departamentos en venta</h2>
    <div class="contenedor-anuncios">
        {% for propiedad in clave %}
            <div class="anuncio"> <!-- anuncio inicio -->
                <picture>
                    {% comment %} <source srcset="{{ propiedad.img.url }}" type="image/webp"> {% endcomment %}
                    <img loading="lazy" width="200" height="300" src="{{ propiedad.img.url }}" alt="Imagen de la propiedad">
                </picture>
                <div class="contenido-anuncio">
                    <h3>{{ propiedad.titulo }}</h3>
                    <p class="alturamin">{{ propiedad.descripcion }}</p>
                    <p><span class="precio">{{ propiedad.precio }}€</span></p>


                    <ul class="iconos-caracteristicas">
                        <li>
                            <img loading="lazy" src="{% static 'img/iconos/icono_dormitorio.svg' %}" alt="icono hanitaciones" />
                            <p>{{ propiedad.habitaciones }}</p>
                        </li>
                        <li>
                            <img loading="lazy" src="{% static 'img/iconos/icono_wc.svg' %}" alt="icono wc" />
                            <p>{{ propiedad.wc }}</p>
                        </li>
                        <li>
                            <img loading="lazy" src="{% static 'img/iconos/icono_estacionamiento.svg' %}" alt="icono estacionamiento" />
                            <p>{{ propiedad.garaje }}</p>
                        </li>
                    </ul>

                    <a href="{% url 'namespaceraices:anuncio_detalles' propiedad.id %}" class="btn-amarillo-block">Ver propiedad</a>
                </div>
            </div> <!-- fin anuncio -->
        {% endfor %}
    </div>
</main>

    {% include "includes/footer.html" %}
</body>

</html>

main/templates/plantillas/contacto.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>
    <main class="form-img">
        <div class="contenedor contenido-contacto">
            <div class="contacto-formulario">
                {% if success %}
                    <div>
                        <p class="success-message">¡Gracias por contactarnos! Nos pondremos en contacto contigo pronto</p>
                    </div>
                {% else %}
                    <form class="form-contact formulario" action="{% url 'namespaceraices:contacto' %}" autocomplete="on" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            <legend>Informacion personal</legend>
                            <div class="group">
                                <div>
                                    <label for="nombre">Nombre completo <span>*</span></label>
                                    {% if request.user.is_authenticated %}
                                        <input id="nombre" type="text" name="nombre" value="{{ request.user.username }}" placeholder="Tu nombre" disabled>
                                        <input id="nombre" type="hidden" name="nombre" value="{{ request.user.username }}">
                                    {% else %}
                                        <input id="nombre" type="text" name="nombre" placeholder="Tu nombre" required>
                                    {% endif %}
                                </div>
                                <!-- aqui el bloque de error de nombre -->
                            </div>

                            <div class="email-phone">
                                <div class="group">
                                    <div>
                                        <label for="email">Email <span>*</span></label>
                                        <input id="email" type="email" name="email" placeholder="Tu email" required>
                                    </div>
                                    <!-- aqui el bloque de error de email -->
                                </div>
                                <div class="group">
                                    <div>
                                        <label for="telefono">Teléfono <span>*</span></label>
                                        <input id="telefono" type="tel" name="telefono" placeholder="Tu teléfono" required>
                                    </div>
                                    <!-- aqui el bloque de error de teléfono -->
                                </div>
                            </div>
                            <div class="group">
                                <div class="textarea-container"> <!-- clase extra para evitar extensiones Chrome -->
                                    <label for="mensaje">Mensaje <span>*</span></label>
                                    <textarea id="mensaje" name="mensaje" placeholder="Escribe un breve mensaje" required></textarea>
                                </div>
                                <!-- aqui el bloque de error de mensaje -->
                            </div>
                        </fieldset>

                        <div class="enviar-formulario">
                            <input type="submit" value="Enviar" class="enviar btn-verde">
                        </div>
                        {% if formContacto.errors %}
                            {{formContacto.errors}}
                        {% endif %} 
                    </form>                                             
                {% endif %}
                    <div class="form-map">
                        <div class="icon-flex">
                            <div>
                                <i class="fa-solid fa-location-dot"></i>
                            </div>
                            <div>
                                <h4>Ubicación</h4>
                                <p>Madrid, España</p>
                            </div>
                        </div>
                        <div class="icon-flex">
                            <div>
                                <i class="fa-solid fa-envelope"></i>
                            </div>
                            <div>
                                <h4>Email</h4>
                                <p>agentes@bienesraices.com</p>
                            </div>
                        </div>
                            <div class="icon-flex final-map">
                            <div>
                                <i class="fa-solid fa-phone"></i>
                            </div>
                            <div>
                                <h4>Teléfono</h4>
                                <p>+34 643 920 193</p>
                            </div>
                        </div>
                        
                        <div class="form-iframe">
                            <iframe 
                                src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d194389.02140733364!2d-3.7276194687773105!3d40.42372525003066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2ses!4v1701038871281!5m2!1ses!2ses" 
                                style="border:0;" 
                                allowfullscreen 
                                loading="lazy">
                            </iframe>
                        </div>

                    </div>
            </div>            
        </div>
    </main>
    
    {% include "includes/footer.html" %}
    <!--=============== JavaScript personalizado ===============-->
    <script src="{% static 'js/contacto.js' %}"></script>
</body>
</html>

main/templates/plantillas/index.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header inicio">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
            <h1>Agencia Inmobiliaria Exclusiva en Venta de Casas y Departamentos</h1>
        </div>
    </header>
    <main class="contenedor">
        <h1>Mas sobre Nosotros</h1>
        <div class="iconos_nosotros">
            <div class="icono">
                <img src="{% static 'img/iconos/icono1.svg' %}" alt="Icono Seguridad" loading="lazy">
                <h3>Seguridad</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
            <div class="icono">
                <img src="{% static 'img/iconos/icono2.svg' %}" alt="Icono Precio" loading="lazy">
                <h3>Precio</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
            <div class="icono">
                <img src="{% static 'img/iconos/icono3.svg' %}" alt="Icono Tiempo" loading="lazy">
                <h3>A Tiempo</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
        </div>
    </main>
    <section class="contenedor">
        <h2>Casas y Departamentos en venta</h2>
        <div class="contenedor-anuncios"> <!-- contenedor inicio -->
            {% for propiedad in solo_tres %}
                <div class="anuncio"> <!-- anuncio inicio -->
                    <picture>
                        {% comment %} <source srcset="{{ propiedad.img.url }}" type="image/webp"> {% endcomment %}
                        <img loading="lazy" width="200" height="300" src="{{ propiedad.img.url }}" alt="Imagen de la propiedad">
                    </picture>
                    <div class="contenido-anuncio">
                        <h3>{{ propiedad.titulo }}</h3>
                        <p class="alturamin">{{ propiedad.descripcion }}</p>
                        <p><span class="precio">{{ propiedad.precio }}€</span></p>

                        <ul class="iconos-caracteristicas">
                            <li>
                                <img loading="lazy" src="{% static 'img/iconos/icono_dormitorio.svg' %}" alt="icono hanitaciones" />
                                <p>{{ propiedad.habitaciones }}</p>
                            </li>
                            <li>
                                <img loading="lazy" src="{% static 'img/iconos/icono_wc.svg' %}" alt="icono wc" />
                                <p>{{ propiedad.wc }}</p>
                            </li>
                            <li>
                                <img loading="lazy" src="{% static 'img/iconos/icono_estacionamiento.svg' %}" alt="icono estacionamiento" />
                                <p>{{ propiedad.garaje }}</p>
                            </li>
                        </ul>

                        <a href="{% url 'namespaceraices:anuncio_detalles' propiedad.id %}" class="btn-amarillo-block">Ver propiedad</a>
                    </div>
                </div> <!-- fin anuncio -->
            {% endfor %}
        </div> <!-- fin contenedor -->

        <div class="ver-todas">
            <a href="{% url 'namespaceraices:anuncios' %}" class="btn-verde">Ver todas</a>
        </div>
    </section>

    <section class="imagen-contacto">
        <div class="contenedor info">
            <h2>Encuentra la casa de tus sueños</h2>
            <p>Llena el formulario de contacto y un asesor se pondrá en contacto contigo</p>
            <a href="{% url 'namespaceraices:contacto' %}" class="btn-amarillo">Contáctanos</a>
        </div>
    </section>

    <div class="contenedor seccion-inferior">
        <section> <!-- section 1 -->
            <h3 class="h3Index">Nuestro Blog</h3>
            {% for blog in solo_dos %}
                <article class="entrada-blog"> <!-- blog Inicio -->
                    <div>
                        <picture>
                            {% if blog.img_webp %}
                                <source srcset="{{ blog.img_webp.url }}" type="image/webp">
                            {% endif %}
                                <img loading="lazy" width="200" height="300" src="{{ blog.img_jpg.url }}" alt="Texto Entrada Blog">
                        </picture>
                    </div>

                    <div class="texto-entrada">
                        <a href="{% url 'namespaceblog:blog_details' blog.id %}">
                            <h4>{{ blog.title }}</h4>
                            <p class="informacion-meta">Escrito el: <span class="spafecha">{{ blog.fecha }}</span> por: <span>{{ blog.nombre_titular }}</span> </p>

                            <p>{{ blog.descripcion }}</p>
                        </a>
                    </div>
                </article>
            {% endfor %}
        </section> <!-- Fin section 1 -->

        <section class="testimoniales"> <!-- section 2 -->
            <h3 class="h3Index">Testimoniales</h3>
            <div class="testimonial">
                {% for testimonial in testimoniales %}
                    <div class="mySlides fade">
                        <q>{{ testimonial.contenido }}</q>
                        <p class="author">- {{ testimonial.usuario.username }}</p>
                    </div>
                {% endfor %}
            </div>
        </section> <!-- Fin section 2 -->
    </div>

    {% include "includes/footer.html" %}
</body>

</html>

main/templates/plantillas/prueba.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                <a href="/"><!-- Otra opción es: "/" -->
                    <img class="logo-header" src="{% static 'img/logo.svg' %}" alt="logo_bienesRaices" />
                </a>

                <div class="extra-mobil">
                    <div class="derecha-btndark"><!-- btn dark -->
                        <img class="dark-mode-btn" src="{% static 'img/dark-mode.svg' %}" />
                    </div>

                    <div class="final-btn">
                        <div class="mobile-menu"> <!-- burger btn -->
                            <img src="{% static 'img/barras.svg' %}" />
                        </div>
                        <div>
                            <nav class="navegacion-header">
                                <a href="{% url 'namespaceraices:nosotros' %}">Acerca de nosotros</a>
                                <a href="{% url 'namespaceraices:anuncios' %}">Anuncios</a>
                                <a href="blog.php">Blog</a>
                                <a href="contacto.php">Contacto</a>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main class="contenedor seccion">
        <h1>Funcionaaa</h1>

    </main>

{% include "includes/footer.html" %}

</body>

</html>

main/templates/plantillas/testimoniales.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>

    <main>
        <div class="principal">
            <section class="section1">
                <div class="probando-img"></div>
            </section>
            <section class="section2">
                <form class="formTestimonials" action="{% url 'namespaceraices:testimonials' %}" method="POST"> <!-- Valida los campos -->
                    {% csrf_token %}
                    <h1>Hola {{ request.user.username }} 👋</h1>
                    <h3>Dejanos una reseña</h3>
                    <p>Puedes escribir un máximo de 250 caracteres</p>
                    <div class="group">
                        <div class="group-testimonials">
                            {% comment %} <input class="input-field" id="email" type="email" name="email"  required> cols="60" rows="10" {% endcomment %}
                            <textarea id="contenido" name="{{ form_testimoniales.contenido.name }}" placeholder="Escribe una breve reseña" required></textarea>
                        </div>
                        <!-- aqui el bloque de error de reseña -->
                    </div>
                    <div class="div-enviar btn-negro">
                        <input class="enviar" type="submit" value="Enviar">
                    </div>
                    {% if form_testimoniales.errors %}
                        {{form_testimoniales.errors}}
                    {% endif %}  
                </form>
            </section>
        </div>
    </main>

    {% include "includes/footer.html" %}

    <!--=============== JavaScript personalizado ===============-->
    <script src="{% static 'js/testimoniales.js' %}"></script>
</body>

</html>