BienesRaices/urls.py
from django.contrib import admin
from django.urls import path, include # include para incluir otras url de otras aplicaciones ejm: 'blog'

# Para acceder a los archivos statics y media desde el navegador.
from django.conf import settings
from django.conf.urls.static import static

""" PARA ACCEDER A LOS ESQUEMAS CREADOS archivo.yml desde la web, tenemos que establecer las url's """
from drf_spectacular.views import (SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView)


# Tambien conocidos como EndPoints => Hablando de documentación de Apis
urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # URL de Autenticacion y Autorización de Django
    path('api/v1/', include("api.urls", namespace ="api-rest")), # Registramos las Urls de nuestra API
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'), # url_name='schema' => el name coincide con el name de SpectacularAPIView.as_view()
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path("", include("main.urls", namespace="main")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("signup-users/", include("users.urls", namespace="signup-users")),
    path("chat/", include("chat.urls", namespace="chat-room")),
    path("social-auth/", include("social_django.urls", namespace="social")),  # <-- Social Media
]

# if settings.DEBUG === True
# Configuración para servir archivos de medios solo durante el desarrollo.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# usamos routers en lugar de path, ya que nos permiten hacer varias operaciones
# que gestiona Django como un CRUD (get, post, delete, etc..)
from rest_framework import routers
from .views import PropiedadesViewSet

app_name = "api_propiedades"

router = routers.DefaultRouter()  # Es clave porque lo gestiona Django (get, post, delete, etc..)
router.register("propiedades", PropiedadesViewSet, "propiedades_api")

urlpatterns = router.urls

blog/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

app_name = "namespaceblog"

urlpatterns = [
    path("", views.viewBlog, name="blog_list"),
    path("<int:id>/", views.viewBlogDetail, name="blog_details"),  # <int:id> una url dinámica con el ID de cada BLOG
    path("blog-register/", views.viewCreateBlog, name="blog-register"),
    path("check_user_createBlog/", views.check_user_createBlog, name="check_user_createBlog"),
]

chat/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

app_name = "namespacechat"

urlpatterns = [
    path("", views.viewHome, name="home"),
    path("room/<int:room_id>/", views.viewRoom, name="room-datail"),
]

users/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

## from django.contrib.auth import views as auth_views  # Importa las vistas de autenticación

app_name = "namespaceusers"

urlpatterns = [
    path("", views.viewLogin, name="login"),
    path("user-register", views.viewSignUp, name="user-register"),
    # path("login/", auth_views.LoginView.as_view(), name="login"),
]

# path("datos-usuario/", views.user_data_and_notes, name="user-dates"),

blog/models.py
from django.db import models
from django.utils import timezone
from users.models import User

# Create your models here.

# table Blog con sus campos title, img, nombre_titular, fecha, descripcion, contenido
class Blog(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    nombre_titular = models.CharField(max_length=50, null=True, blank=True)
    img_jpg = models.ImageField(upload_to="blog/", verbose_name="Imagen JPG") # null=True, blank=True => blank indica que el campo no es obligatorio
    img_webp = models.ImageField(upload_to="blog/", verbose_name="Imagen WEBP", null=True, blank=True)
    fecha = models.DateField(default=timezone.now)  # Valor por defecto: fecha actual
    descripcion = models.CharField(max_length=260)
    contenido = models.TextField()

    # Para tener una mejor visualizacion en la interfaz del admin
    # Es opcional, ya que se mejora en el admin.py
    def __str__(self):
        return self.title
    # Devuelve el nombre como su representación de cadena
    
    
    
# AQUI ES MEJOR USAR DIRECTAMENTE EL ResizedImageField(Size[600,600], quality=85, upload_to...)   

blog/forms.py
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError

# OBLIGATORIO, si queremos que se registre en la DB, debemos inportar como en admin.py
from .models import Blog
from django.utils.html import escape  # para escapar codigo malisioso

from PIL import Image
import io
from django.core.files.uploadedfile import InMemoryUploadedFile

# class BlogForm (forms.Form): => de formulario regular a PERSISTENTE
class BlogForm(forms.ModelForm):
    title = forms.CharField(
        label="Título del blog", 
        max_length=50,
        required=True,
    )
    nombre_titular = forms.CharField(
        label="Nombre del titular",
        max_length=50,
        required=False,
        # disabled=True,
    )
    img_jpg = forms.ImageField(
        label="Imagen JPG",
        widget=forms.FileInput(attrs={"accept": ".jpg"}),
    )
    img_webp = forms.ImageField(
        label="Imagen WEBP",
        widget=forms.FileInput(attrs={"accept": ".webp"}),
        required=False,
    )
    fecha = forms.DateField(
        label="Fecha",
        widget=forms.DateInput(attrs={"type": "date"}),
        disabled=True,
        initial=timezone.now().date(),  # Establece la fecha actual como valor inicial
    )
    descripcion = forms.CharField(label="Descripción", max_length=260, required=True)
    contenido = forms.CharField(label="Contenido", widget=forms.Textarea, required=True)

    def clean_title(self):
        title = self.cleaned_data["title"].strip()
        if len(title.split()) > 10:
            raise forms.ValidationError("El título no debe exceder las 10 palabras")
        return escape(title)

    # def clean_nombre_titular => por defecto de sesion

    def clean_descripcion(self):
        descripcion = self.cleaned_data["descripcion"].strip()
        if len(descripcion.split()) > 22:
            raise forms.ValidationError("La descripción no debe exceder las 22 palabras")
        return escape(descripcion)

    def clean_contenido(self):
        contenido = self.cleaned_data["contenido"].strip()
        return escape(contenido)

    def clean_img_jpg(self):
        img_jpg = self.cleaned_data.get("img_jpg")
        if img_jpg:
            if img_jpg.size > 100 * 1024:
                raise forms.ValidationError("La imagen JPG debe ser menor de 100 KB.")
            if not img_jpg.name.endswith(".jpg"):
                raise forms.ValidationError("La imagen JPG debe tener extensión .jpg")
            self._resize_image(img_jpg)
        return img_jpg

    def clean_img_webp(self):
        img_webp = self.cleaned_data.get("img_webp")
        if img_webp:
            if img_webp.size > 100 * 1024:
                raise forms.ValidationError("La imagen WEBP debe ser menor de 100 KB.")
            if not img_webp.name.endswith(".webp"):
                raise forms.ValidationError("La imagen WEBP debe tener extensión .webp")
            self._resize_image(img_webp)
        return img_webp

    def _resize_image(self, image_field):
        image = Image.open(image_field)
        original_width, original_height = image.size
        target_width, target_height = 600, 450

        # Primero redimensionar la imagen manteniendo el aspecto
        image.thumbnail((target_width, target_height), Image.Resampling.LANCZOS)

        # Luego recortar la imagen centrada si no coincide con las dimensiones exactas
        left = (image.width - target_width) / 2
        top = (image.height - target_height) / 2
        right = (image.width + target_width) / 2
        bottom = (image.height + target_height) / 2

        image = image.crop((left, top, right, bottom))

        # Determinar el formato basado en la extensión del archivo
        extension = image_field.name.split('.')[-1].lower()
        format_dict = {'jpg': 'JPEG', 'jpeg': 'JPEG', 'webp': 'WEBP'}
        image_format = format_dict.get(extension, 'JPEG')

        image_io = io.BytesIO()
        image.save(image_io, format=image_format)
        image_file = InMemoryUploadedFile(image_io, None, image_field.name, image_format, image_io.tell, None)
        image_field.file = image_file

    def clean(self):
        cleaned_data = super().clean()
        img_jpg = cleaned_data.get("img_jpg")
        img_webp = cleaned_data.get("img_webp")

        if not img_jpg and not img_webp:
            raise ValidationError("Debe cargar al menos una imagen.")

        return cleaned_data

    class Meta:
        model = Blog
        fields = [
            "title",
            "nombre_titular",
            "img_jpg",
            "img_webp",
            "fecha",
            "descripcion",
            "contenido",
        ]


# def _resize_image(self, image_field):
#     image = Image.open(image_field)
#     original_width, original_height = image.size
#     target_width, target_height = 600, 450

#     # Calcular las proporciones de la imagen original y las dimensiones objetivo
#     original_ratio = original_width / original_height
#     target_ratio = target_width / target_height

#     # Si la proporción original es mayor que la proporción objetivo,
#     # significa que la imagen es más ancha, entonces cortamos los lados
#     if original_ratio > target_ratio:
#         new_width = int(target_ratio * original_height)
#         offset = (original_width - new_width) // 2
#         image = image.crop((offset, 0, offset + new_width, original_height))
#     # Si la proporción original es menor que la proporción objetivo,
#     # significa que la imagen es más alta, entonces cortamos la parte superior e inferior
#     elif original_ratio < target_ratio:
#         new_height = int(original_width / target_ratio)
#         offset = (original_height - new_height) // 2
#         image = image.crop((0, offset, original_width, offset + new_height))
#     # Si las proporciones son iguales, no hacemos ningún recorte

#     # Redimensionar la imagen
#     image = image.resize((target_width, target_height), Image.Resampling.LANCZOS)

#     # Determinar el formato basado en la extensión del archivo
#     extension = image_field.name.split(".")[-1].lower()
#     format_dict = {"jpg": "JPEG", "jpeg": "JPEG", "webp": "WEBP"}
#     image_format = format_dict.get(extension, "JPEG")

#     image_io = io.BytesIO()
#     image.save(image_io, format=image_format)
#     image_file = InMemoryUploadedFile(
#         image_io, None, image_field.name, image_format, image_io.tell, None
#     )
#     image_field.file = image_file

blog/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib import messages
from django.http import JsonResponse
from chat.models import Room  # Importa el Room User de la app chat
from django.utils import timezone

# descorador para validar si el usuario esta autenticado
from django.contrib.auth.decorators import login_required

# Importamos los modelos o formularios
from .models import Blog
from .forms import BlogForm

# Create your views here.

def viewBlog(request):
    # Traemos la sala de chat
    ## => room = Room.objects.first()
    # Query de los blogs
    query_result = Blog.objects.all().order_by("-id")[:4]

    return render(
        request, "plantillas_blog/blog.html", {"clave": query_result} ## => , "room": room
    )


def viewBlogDetail(request, id):
    try:
        # busca el registro cuyo ID es igual al pasado por URL
        query_result = Blog.objects.get(id=id)
    except Blog.DoesNotExist:
        # Si no existe ese ID lanza la excepcion DoesNotExist y capturada con un try-except
        raise Http404("La publicación del blog no existe")

    return render(request, "plantillas_blog/blog_detail.html", {"blog_detail": query_result})


# descorador para validar si el usuario esta autenticado
@login_required
def viewCreateBlog(request):

    user = request.user

    # Verificar si el usuario ya tiene un blog escrito
    if Blog.objects.filter(usuario=user).exists():
        messages.error(request, "Ya has escrito un blog.")

    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES)
        if (form.is_valid()):  # valida  los campos del formulario, que no esten vacion, etc

            # Si el formulario es válido, guardamos el blog en la base de datos
            new_blog = form.save(commit=False)
            new_blog.nombre_titular = request.user.username  # Establecer el nombre del titular como el nombre de usuario autenticado
            new_blog.usuario = (request.user)
            new_blog.save()

            # Guarda el nuevo registro en BD
            new_blog = form.save()

            messages.success(request, "Publicacion creada con éxito!")
            # Redirecciona a un Url
            return redirect("namespaceblog:blog_details", id=new_blog.id)
    else:
        current_date = timezone.now().date()  # Obtener la fecha actual
        formatted_date = current_date.strftime("%Y-%m-%d")  # Formatear la fecha en el formato YYYY-MM-DD
        initial_data = {
            "nombre_titular": request.user.username,
            "fecha": formatted_date,
        }  # Establecer el valor inicial del campo nombre_titular como el nombre de usuario autenticado
        form = BlogForm(initial=initial_data)  # Pasar la fecha actual como valor inicial para el campo de fecha

    return render(request, "plantillas_blog/create_blog.html", {"registrar_blog": form})


# Endpoind de verificacion de usuario y evitar que vuelva a escribir
@login_required
def check_user_createBlog(request):
    user = request.user
    has_blog = Blog.objects.filter(usuario=user).exists()
    return JsonResponse({"has_blog": has_blog})

blog/templates/plantillas_blog/blog.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>
    <main class="contenedor sidebar">
        <div class="entrada-bienvenido">
            {% if request.user.is_authenticated %}
                <div>
                    <h1>Nuestro Blog</h1>
                </div>
            {% comment %} 
                <div class="entrada-sesion">
                    <div>
                        <p>Bienvenido {{ request.user.username }}</p>
                        <a href="{% url 'namespacechat:room-datail' room.id %}">{{ room.name }}</a>
                    </div>
                    <div>
                        <p ><a href="{% url 'namespaceblog:blog-register' %}">Publicar blog</a></p>
                    </div> 
                </div>
            {% endcomment %}          
            {% else %}
                <div class="entrada-nosesion">
                    <div class=""> 
                        <p>¿Te gustaria ser parte de nuestra comunidad?</p>
                        <p>¿Quieres publicar un blog?</p>
                        <p><a href="{% url 'namespaceusers:user-register' %}">¡Registrate!</a></p>
                    </div>
                </div>
            {% endif %}
        </div>

        {% for post in clave %}
            <article class="entrada-blog"> <!-- entrada-blog -->
                <div>
                    <picture>
                        {% if post.img_webp %}
                            <source srcset="{{post.img_webp.url}}" type="image/webp">
                        {% endif %}
                            <img loading="lazy" width="200" height="300" src="{{ post.img_jpg.url }}" alt="Imagen Blog">    
                    </picture>
                </div>

                <div class="texto-entrada">
                    <a href="{% url 'namespaceblog:blog_details' post.id %}">
                        <h4>{{ post.title }}</h4>
                        <p class="informacion-meta">Escrito el: <span class="spafecha">{{ post.fecha }}</span> por: <span>{{ post.nombre_titular }}</span> </p>

                        <p>{{ post.descripcion }}</p>
                    </a>
                </div>
            </article>
        {% endfor %}
    </main>
    {% include "includes/footer.html" %}
</body>

</html>

blog/templates/plantillas_blog/blog_detail.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>

    <main class="contenedor details"> {% comment %} contenido-centrado comodin {% endcomment %}
        <h1>{{ blog_detail.title }}</h1>
        <div class="div_blogDetails">
            <picture>
                {% if blog_detail.img_webp %}
                    <source srcset="{{blog_detail.img_webp.url}}" type="image/webp">
                {% endif %} 
                    <img loading="lazy" width="200" height="300" src="{{ blog_detail.img_jpg.url }}" alt="Imagen Blog">
            </picture>

            <div>
                <p class="informacion-meta">Escrito el: <span>{{ blog_detail.fecha }}</span> por: <span>{{ blog_detail.nombre_titular }}</span></p>

                <p>{{ blog_detail.contenido }}</p>
            </div>
        </div>
    </main>

    {% include "includes/footer.html" %}
</body>

</html>

blog/templates/plantillas_blog/create_blog.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

{% include "includes/head.html" %}

<body>
    <header class="header">
        <div class="contenedor contenido-header">
            <div class="barra">
                {% include "includes/barra_movil.html" %}
            </div>
        </div>
    </header>
    <main>
        <div class="principal">
            <section class="section1">
                <div class="probando-img"></div>
            </section>
            <section class="section2">
            <form class="formCreatedBlog" action="{% url 'namespaceblog:blog-register' %}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Registrar un nuevo Blog</h1>

                <div class="div-createBlog">
                    <div class="group">
                        <div class="group-createBlog">
                            <label for="name">Nombre del titular</label>
                            <input id="name" type="text" name="{{ registrar_blog.nombre_titular.name }}" value="{{ registrar_blog.nombre_titular.value }}" maxlength="50" disabled>
                        </div>
                        <!-- aqui el bloque de error de Nombre del titulars -->
                    </div>

                    <div class="group">
                        <div class="group-createBlog">
                            <label for="title">Título del blog <span>*</span></label>
                            <input id="title" type="text" name="{{ registrar_blog.title.name }}" maxlength="50" required>
                        </div>
                        <!-- aqui el bloque de error de nombre del título -->
                    </div>

                    <div class="group">
                        <div class="group-createBlog">
                            <label for="img_jpg">Imagen JPG <span>* obligatorio</span></label>
                            <input id="img_jpg" type="file" name="{{ registrar_blog.img_jpg.name }}" accept=".jpg" required >
                        </div>
                        <!-- aqui el bloque de error de Imagen JPG * -->
                    </div>

                    <div class="group">
                        <div class="group-createBlog">
                            <label for="img_webp">Imagen WEBP</label>
                            <input id="img_webp" type="file" name="{{ registrar_blog.img_webp.name }}" accept=".webp">
                        </div>
                        <!-- aqui el bloque de error de Imagen WEBP * -->
                    </div>

                    <div class="group">
                        <div class="group-createBlog">
                            <label for="descripcion">Descripción <span>*</span></label>
                            <input id="descripcion" type="text" name="{{ registrar_blog.descripcion.name }}" maxlength="260" required>
                        </div>
                        <!-- aqui el bloque de error de Descripción -->
                    </div>

                    <div class="group">
                        <div class="group-createBlog">
                            <label for="fecha">Fecha</label>
                            <input id="fecha" type="date" name="{{ registrar_blog.fecha.name }}" value="{{ registrar_blog.fecha.value }}" disabled>
                        </div>
                        <!-- aqui el bloque de error de Fecha -->
                    </div>
                </div>

                <div class="group">
                    <div class="group-createBlog">
                        <label for="contenido">Contenido <span>*</span></label>
                        <textarea id="contenido" name="{{ registrar_blog.contenido.name }}" cols="40" rows="10" required></textarea>
                    </div>
                    <!-- aqui el bloque de error de Contenido -->
                </div>

                <div class="div-enviar btn-negro">
                    <input class="enviar" type="submit" value="Crear Blog">
                </div>
                {% if registrar_blog.errors %}
                    {{registrar_blog.errors}}
                {% endif %}  
            </form>
            </section>
        </div>             
    </main>

{% include "includes/footer.html" %}
<!--=============== JavaScript personalizado ===============-->
<script src="{% static 'js/createdBlog.js' %}"></script>
</body>

</html>