BienesRaices/urls.py
from django.contrib import admin
from django.urls import path, include # include para incluir otras url de otras aplicaciones ejm: 'blog'

# Para acceder a los archivos statics y media desde el navegador.
from django.conf import settings
from django.conf.urls.static import static

""" PARA ACCEDER A LOS ESQUEMAS CREADOS archivo.yml desde la web, tenemos que establecer las url's """
from drf_spectacular.views import (SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView)


# Tambien conocidos como EndPoints => Hablando de documentación de Apis
urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # URL de Autenticacion y Autorización de Django
    path('api/v1/', include("api.urls", namespace ="api-rest")), # Registramos las Urls de nuestra API
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'), # url_name='schema' => el name coincide con el name de SpectacularAPIView.as_view()
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path("", include("main.urls", namespace="main")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("signup-users/", include("users.urls", namespace="signup-users")),
    path("chat/", include("chat.urls", namespace="chat-room")),
    path("social-auth/", include("social_django.urls", namespace="social")),  # <-- Social Media
]

# if settings.DEBUG === True
# Configuración para servir archivos de medios solo durante el desarrollo.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# usamos routers en lugar de path, ya que nos permiten hacer varias operaciones
# que gestiona Django como un CRUD (get, post, delete, etc..)
from rest_framework import routers
from .views import PropiedadesViewSet

app_name = "api_propiedades"

router = routers.DefaultRouter()  # Es clave porque lo gestiona Django (get, post, delete, etc..)
router.register("propiedades", PropiedadesViewSet, "propiedades_api")

urlpatterns = router.urls

blog/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

app_name = "namespaceblog"

urlpatterns = [
    path("", views.viewBlog, name="blog_list"),
    path("<int:id>/", views.viewBlogDetail, name="blog_details"),  # <int:id> una url dinámica con el ID de cada BLOG
    path("blog-register/", views.viewCreateBlog, name="blog-register"),
    path("check_user_createBlog/", views.check_user_createBlog, name="check_user_createBlog"),
]

chat/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas

app_name = "namespacechat"

urlpatterns = [
    path("", views.viewHome, name="home"),
    path("room/<int:room_id>/", views.viewRoom, name="room-datail"),
]

main/urls.py
from django.urls import path  # path nos permite crear las urls que necesitemos
from . import views  # me traigo todas las vistas
# Tambien se puede acceder => views.my_main.etc

app_name = "namespaceraices"

urlpatterns = [
    path("", views.my_main, name="main"),
    path("nosotros/", views.nosotros, name="nosotros"),
    path("anuncios/", views.anuncios, name="anuncios"),
    path("<int:id>/", views.anuncio_detalles, name="anuncio_detalles"),
    path("contacto/", views.contacto, name="contacto"),
    path("testimoniales/", views.viewTestimoniales, name="testimonials"),
    path("check_user_testimonial/", views.check_user_testimonial, name="check_user_testimonial"),
]

templates/includes/barra_movil.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

<!-- Logo -->
<a href="{% url 'namespaceraices:main' %}"><!-- Otra opción es: "/" -->
    <img class="logo-header" src="{% static 'img/logo.svg' %}" alt="logo_bienesRaices" />
</a>

<!--------- Div extra --------->
<div class="extra-mobil">
    <!-- btn dark -->
    <div class="derecha-btndark">
        <div class="separa-logo">
            <div class ="position-user">
                {% if request.user.is_authenticated %}
                <div class="sidebar-desplegable">
                    <p class="user-logged">{{ request.user.username }}</p>
                    <i class="fa-solid fa-caret-down"></i>
                </div>
                <div class="dropdown-user">
                    <div id="mySibar" class="siderbar-user">
                        <nav class="navegacion-sidebar">
                            {% if request.user.is_superuser %}
                            <a href="{% url 'admin:index' %}">Portal Admin</a>
                            {% endif %}
                            <a href="{% url 'namespaceblog:blog-register' %}">Publicar un post</a>
                            {% comment %} <a href="{% url 'namespacechat:home' %}">Sala de chat</a>  Solo en local {% endcomment %}
                            <a href="{% url 'namespaceraices:testimonials' %}">Escribir una reseña</a>
                            <a href="{% url 'logout' %}">Cerrar sesión</a>
                        </nav>
                    </div>
                </div>
                {% endif %}
            </div>
            <i class="fa-solid fa-moon dark-mode-btn" id="icon-moon"></i>
        </div>
    </div>
    <!-- burger btn -->
    <div class="final-btn">
        <div class="mobile-menu"> 
            <img src="{% static 'img/barras.svg' %}" />
        </div>
        <div class="dropdown">
            <div id="myDropdown" class="dropdown-content">
                <nav class="navegacion-header">
                    <a href="{% url 'namespaceraices:nosotros' %}">Acerca de nosotros</a>
                    <a href="{% url 'namespaceraices:anuncios' %}">Anuncios</a>
                    <a href="{% url 'namespaceblog:blog_list' %}">Blog</a>
                    <a href="{% url 'namespaceraices:contacto' %}">Contacto</a>
                    {% if request.user.is_authenticated %}
                        <div class="icon-wrapper">
                            <a href="{% url 'logout' %}" class="icon-default">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                            <a href="{% url 'logout' %}" class="icon-hover">
                                <i class="fa-solid fa-person-walking-dashed-line-arrow-right"></i>
                            </a>
                        </div>
                    {% else %}
                        <a href="{% url 'login' %}">Inicia sesión</a>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
</div>                

templates/includes/footer.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

<footer class="footer">
    <div class="div-footer contenedor">
        <div class="contenido-footer">
            <nav class="navegacion-footer">
                <a href="{% url 'namespaceraices:nosotros' %}">Acerca de nosotros</a>
                <a href="{% url 'namespaceraices:anuncios' %}">Anuncios</a>
                <a href="{% url 'namespaceblog:blog_list' %}">Blog</a>
                <a href="{% url 'namespaceraices:contacto' %}">Contacto</a> 
            </nav>
        </div>
        <p class="copyright">&copy; Todos los derechos reservados 2024</p>
    </div>
</footer>

<!--=============== JavaScript personalizado ===============-->
<script src="{% static 'js/bundle.js' %}"></script>

templates/includes/head.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="author" content="Cristian Eduardo Castro Vargas">
    <meta name="description" content="Real-Estate-Project">
    <title>Bienes Raíces</title>

    <!-- Favicons -->
    <link href="{% static 'img/Br-logo.png' %}" rel="icon" type="image/x-icon">
    <link href="{% static 'img/Br-apple.png' %}" rel="apple-touch-icon">

    <!--=============== Bibliotecas y frameworks ===============-->
    <script src="https://kit.fontawesome.com/46cf9b25f7.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!--=============== CSS - Global ===============-->
    <link rel="preload" href="{% static 'css/app.css' %}" as="style">
    <link rel="stylesheet" href="{% static 'css/app.css' %}?v=6" />
    {% block head %}{% endblock head %}
</head>
{% block body %}{% endblock body %}

templates/includes/mas_nosotros.html
{% load static %} {% comment %} Cargar los archivos estaticos {% endcomment %}

<section class="contenedor seccion">
        <h1>Mas sobre Nosotros</h1>
        <div class="iconos_nosotros">
            <div class="icono">
                <img src="{% static 'img/iconos/icono1.svg' %}" alt="Icono Seguridad" loading="lazy">
                <h3>Seguridad</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
            <div class="icono">
                <img src="{% static 'img/iconos/icono2.svg' %}" alt="Icono Precio" loading="lazy">
                <h3>Precio</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
            <div class="icono">
                <img src="{% static 'img/iconos/icono3.svg' %}" alt="Icono Tiempo" loading="lazy">
                <h3>A Tiempo</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipiscing elit neque hac tristique, a nisl purus ultrices nunc accumsan molestie etiam habitant eros curae, orci aliquam at sociosqu fames convallis pharetra ut eleifend.</p>
            </div>
        </div>
    </section>